-- Oracle setup script for Warehouse Management ISI.
-- Run this in SQL Developer while connected to the schema used by the web app.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE Logs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Comenzi CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Evaluari CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Materiale CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Transportatori CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Furnizori CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Clienti CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Angajati CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Utilizatori CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE angajati_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE clienti_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE furnizori_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE transportatori_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE materiale_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE comanda_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE evaluare_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE logs_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE utilizatori_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE Utilizatori (
    ID_UTILIZATOR NUMBER PRIMARY KEY,
    UTILIZATOR VARCHAR2(50) NOT NULL UNIQUE,
    PAROLA VARCHAR2(100) NOT NULL,
    ROL VARCHAR2(20) NOT NULL CHECK (ROL IN ('admin', 'user'))
);

CREATE TABLE Angajati (
    ID_ANGAJAT NUMBER PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    FUNCTIE VARCHAR2(100) NOT NULL,
    DATE_DE_CONTACT VARCHAR2(150) NOT NULL
);

CREATE TABLE Clienti (
    ID_CLIENT NUMBER PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    ADRESA VARCHAR2(200) NOT NULL,
    CONTACT VARCHAR2(150) NOT NULL
);

CREATE TABLE Furnizori (
    ID_FURNIZOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    ADRESA VARCHAR2(200) NOT NULL,
    CONTACT VARCHAR2(150) NOT NULL
);

CREATE TABLE Transportatori (
    ID_TRANSPORTATOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    CONTACT VARCHAR2(150) NOT NULL,
    PRET_PE_KG NUMBER(10, 2) NOT NULL CHECK (PRET_PE_KG >= 0)
);

CREATE TABLE Materiale (
    ID_MATERIAL NUMBER PRIMARY KEY,
    NUME VARCHAR2(100) NOT NULL,
    DESCRIERE VARCHAR2(500),
    CANTITATE_IN_STOC NUMBER NOT NULL CHECK (CANTITATE_IN_STOC >= 0),
    PRET_UNITAR NUMBER(10, 2) NOT NULL CHECK (PRET_UNITAR >= 0),
    ID_FURNIZOR NUMBER NOT NULL,
    CONSTRAINT FK_MATERIALE_FURNIZORI FOREIGN KEY (ID_FURNIZOR) REFERENCES Furnizori(ID_FURNIZOR)
);

CREATE TABLE Evaluari (
    ID_EVALUARE NUMBER PRIMARY KEY,
    ID_CLIENT NUMBER NOT NULL,
    SCOR NUMBER NOT NULL CHECK (SCOR BETWEEN 1 AND 5),
    FEEDBACK VARCHAR2(500),
    DATA_EVALUARII DATE NOT NULL,
    CONSTRAINT FK_EVALUARI_CLIENTI FOREIGN KEY (ID_CLIENT) REFERENCES Clienti(ID_CLIENT)
);

CREATE TABLE Comenzi (
    ID_COMANDA NUMBER PRIMARY KEY,
    DATA_COMENZII DATE NOT NULL,
    ID_CLIENT NUMBER NOT NULL,
    ID_FURNIZOR NUMBER NOT NULL,
    ID_ANGAJAT NUMBER NOT NULL,
    ID_MATERIAL NUMBER NOT NULL,
    TOTAL_COMANDA NUMBER(12, 2) NOT NULL CHECK (TOTAL_COMANDA >= 0),
    STATUT_COMANDA VARCHAR2(50) NOT NULL,
    TIP_COMANDA VARCHAR2(50) NOT NULL,
    CANTITATE NUMBER NOT NULL CHECK (CANTITATE > 0),
    PRET_TOTAL NUMBER(12, 2) NOT NULL CHECK (PRET_TOTAL >= 0),
    ID_TRANSPORTATOR NUMBER NOT NULL,
    CONSTRAINT FK_COMENZI_CLIENTI FOREIGN KEY (ID_CLIENT) REFERENCES Clienti(ID_CLIENT),
    CONSTRAINT FK_COMENZI_FURNIZORI FOREIGN KEY (ID_FURNIZOR) REFERENCES Furnizori(ID_FURNIZOR),
    CONSTRAINT FK_COMENZI_ANGAJATI FOREIGN KEY (ID_ANGAJAT) REFERENCES Angajati(ID_ANGAJAT),
    CONSTRAINT FK_COMENZI_MATERIALE FOREIGN KEY (ID_MATERIAL) REFERENCES Materiale(ID_MATERIAL),
    CONSTRAINT FK_COMENZI_TRANSPORTATORI FOREIGN KEY (ID_TRANSPORTATOR) REFERENCES Transportatori(ID_TRANSPORTATOR)
);

CREATE TABLE Logs (
    ID_LOG NUMBER PRIMARY KEY,
    UTILIZATOR VARCHAR2(50),
    ROL VARCHAR2(20),
    DATA_ORA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACTIUNE_LOGICA VARCHAR2(100),
    COMANDA_SQL VARCHAR2(1000)
);

CREATE SEQUENCE utilizatori_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE angajati_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE clienti_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE furnizori_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE transportatori_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE materiale_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE comanda_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE evaluare_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE logs_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_utilizatori_id
BEFORE INSERT ON Utilizatori
FOR EACH ROW
BEGIN
    IF :NEW.ID_UTILIZATOR IS NULL THEN
        :NEW.ID_UTILIZATOR := utilizatori_seq.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_angajati_id
BEFORE INSERT ON Angajati
FOR EACH ROW
BEGIN
    IF :NEW.ID_ANGAJAT IS NULL THEN
        :NEW.ID_ANGAJAT := angajati_seq.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_clienti_id
BEFORE INSERT ON Clienti
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENT IS NULL THEN
        :NEW.ID_CLIENT := clienti_seq.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_furnizori_id
BEFORE INSERT ON Furnizori
FOR EACH ROW
BEGIN
    IF :NEW.ID_FURNIZOR IS NULL THEN
        :NEW.ID_FURNIZOR := furnizori_seq.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_transportatori_id
BEFORE INSERT ON Transportatori
FOR EACH ROW
BEGIN
    IF :NEW.ID_TRANSPORTATOR IS NULL THEN
        :NEW.ID_TRANSPORTATOR := transportatori_seq.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_logs_id
BEFORE INSERT ON Logs
FOR EACH ROW
BEGIN
    IF :NEW.ID_LOG IS NULL THEN
        :NEW.ID_LOG := logs_seq.NEXTVAL;
    END IF;
END;
/

INSERT INTO Utilizatori (UTILIZATOR, PAROLA, ROL) VALUES ('admin', 'admin123', 'admin');
INSERT INTO Utilizatori (UTILIZATOR, PAROLA, ROL) VALUES ('user', 'user123', 'user');

INSERT INTO Angajati (NUME, FUNCTIE, DATE_DE_CONTACT) VALUES ('Popescu Andrei', 'Manager depozit', 'andrei.popescu@example.com');
INSERT INTO Angajati (NUME, FUNCTIE, DATE_DE_CONTACT) VALUES ('Ionescu Maria', 'Operator stoc', 'maria.ionescu@example.com');

INSERT INTO Clienti (NUME, ADRESA, CONTACT) VALUES ('Construct Plus SRL', 'Bucuresti, Str. Industriei 10', 'contact@constructplus.ro');
INSERT INTO Clienti (NUME, ADRESA, CONTACT) VALUES ('Renovari Expert SRL', 'Cluj-Napoca, Str. Fabricii 7', 'office@renovari-expert.ro');

INSERT INTO Furnizori (NUME, ADRESA, CONTACT) VALUES ('Metal Distribution SRL', 'Brasov, Str. Depozitului 3', 'metal@example.com');
INSERT INTO Furnizori (NUME, ADRESA, CONTACT) VALUES ('Lemn & Structuri SRL', 'Timisoara, Calea Aradului 20', 'lemn@example.com');

INSERT INTO Transportatori (NUME, CONTACT, PRET_PE_KG) VALUES ('Rapid Cargo', 'rapid@example.com', 1.25);
INSERT INTO Transportatori (NUME, CONTACT, PRET_PE_KG) VALUES ('TransDepo', 'transdepo@example.com', 1.10);

INSERT INTO Materiale (ID_MATERIAL, NUME, DESCRIERE, CANTITATE_IN_STOC, PRET_UNITAR, ID_FURNIZOR)
VALUES (materiale_seq.NEXTVAL, 'Ciment', 'Saci ciment 40kg', 250, 32.50, 1);
INSERT INTO Materiale (ID_MATERIAL, NUME, DESCRIERE, CANTITATE_IN_STOC, PRET_UNITAR, ID_FURNIZOR)
VALUES (materiale_seq.NEXTVAL, 'Grinzi lemn', 'Grinzi pentru structuri usoare', 80, 115.00, 2);

INSERT INTO Evaluari (ID_EVALUARE, ID_CLIENT, SCOR, FEEDBACK, DATA_EVALUARII)
VALUES (evaluare_seq.NEXTVAL, 1, 5, 'Livrare rapida si materiale conforme.', SYSDATE);
INSERT INTO Evaluari (ID_EVALUARE, ID_CLIENT, SCOR, FEEDBACK, DATA_EVALUARII)
VALUES (evaluare_seq.NEXTVAL, 2, 4, 'Comanda procesata corect.', SYSDATE);

INSERT INTO Comenzi (
    ID_COMANDA, DATA_COMENZII, ID_CLIENT, ID_FURNIZOR, ID_ANGAJAT, ID_MATERIAL,
    TOTAL_COMANDA, STATUT_COMANDA, TIP_COMANDA, CANTITATE, PRET_TOTAL, ID_TRANSPORTATOR
) VALUES (
    comanda_seq.NEXTVAL, SYSDATE, 1, 1, 1, 1, 325.00, 'Procesata', 'Achizitie', 10, 325.00, 1
);

COMMIT;
